name: HotQuant
favicon: null
layout_spectrum: 0.8
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff2626'
    - '#ffcbcb'
    - '#ff6b6b'
    - '#808080'
  brandStrength: 1
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
