typography_spectrum: 0.005000733071938157
content_rating:
  adult: false
color:
  brandColors:
    - '#000000'
    - '#ff6666'
    - '#ffcbcb'
    - '#7f7f7f'
    - '#424242'
  brandStrength: 1
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4037092188373208
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/65bc8f52-3dec-4c0d-b031-77696f252bd5.png
name: HotQuant
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e7ba0263-e5f4-4b89-a61c-b8dde4556542.ico
title: HotQuant
description: Sometimes it does take a rocket scientist.
purpose: []
